### PR TITLE
Fix install errors

### PR DESCRIPTION
**Pull request by cameron1729**
# Testing
1. Ensure the plugin can be installed

### CODE REVIEW

**Comment by darrencocco** [comment]
Only notes are that the licence is LGPLv3 and shouldn't the copyright be Monash Uni since they're the ones paying for it?

**Comment by cameron1729** [comment]
Re: The license, are you OK with leaving the license out of source files and just deferring to the LICENSE file?

Re: Copyright, no issue with that either - can you please give an example of how you'd prefer that line to be written?

**Comment by darrencocco** [comment]
Re: Licence, yeah sounds good.
Re: Copyright,  `* @copyright 2023 Monash University`

**Comment by cameron1729** [comment]
Branch updated.

**Comment by darrencocco** [comment]
Dude, keep the author string. You still deserve props for writing it even if you were paid for it.

**Comment by cameron1729** [comment]
Readded :)

**Review by darrencocco — APPROVED** [review]
Looks good.

**Pull request merged**
